### ISSUE TITLE
tried running it

### ISSUE THREAD

**Issue by a-villain** [MirisWisdom/GShade.Nuke#1]
i tried running it and nothing happened, gshade folders and files are still there.

**Comment by MirisWisdom** [comment]
Hey friend, thanks for giving it a shot and reporting the issue!

Just a few questions:

- Did it create a backup ZIP on your desktop? What files do you see in it?

- Do you still see the GShade folder in `C:\Program Files`? If you do, could you try running the thingy as an administrator?

Cheers,

Miris

**Comment by a-villain** [comment]
no back up zip folder and yes the gshade folder is still in program files

**Comment by MirisWisdom** [comment]
Interesting, hmm... can you open up a Command Line/PowerShell window and manually run the program from it? Easiest way would be to:

1. Windows + R, then type in `cmd`; then
2. Type in the `"C:\Path\To\gshade-nuke.exe"`

And then send me a screenshot of what you see in the window -- curious if errors appear before the program actually does its thing!

**Comment by a-villain** [comment]
ok so, realized i needed all the assets downloaded and not just the exe, my bad, but now this is the error i'm recieving

![image](https://user-images.githubusercontent.com/124875144/218318896-ad9aafe2-4a2c-4cc5-838b-bb6d2c6462bf.png)

**Comment by MirisWisdom** [comment]
Hey friend, cheers for capturing the error. I've released [an update](https://github.com/MirisWisdom/GShade.Nuke/releases/tag/v0.3.0) which will hopefully handle that scenario better. To keep things safe, place `gshade-nuke` in your XIV `game` folder before running it.

The error happened because you've ran the official GShade uninstaller before, which deleted some stuff that GShade Nuke needs.

Many thanks for taking your time to test this out -- it helps tremendously!

> PS: If by assets you're referring to the `.sig` file, that one's simply to verify the download :P

**Comment by d3aths** [comment]
same thing here. i put the nuke in the game's directory, with all these files
![image](https://user-images.githubusercontent.com/16113944/225523287-ec6cd9df-8d2d-46b6-adfb-b1bec3882954.png)

(ive just updated the game after not playing for a year so i think a that d3d file is missing but all g)

running it via command like you instructed on this post gets this info
![image](https://user-images.githubusercontent.com/16113944/225523792-1eec8a75-cde3-4617-8857-e5819dfbd41e.png)

get this log created after trying to run it that simply says

```
at Miris.GShade.Nuke.Program.Localise()
at Miris.GShade.Nuke.Program.Main(String[] args)
```

**Comment by MirisWisdom** [comment]
Thank you for reporting the quirk -- I'll try to figure out what could possibly cause that and release an update as soon as possible. Welcome back to XIV!

**Comment by MirisWisdom** [comment]
@d3aths, could you try the [latest version](https://github.com/MirisWisdom/GShade.Nuke/releases/latest)? It probably won't fix the error; however, it should show more information in the log file.

**Comment by d3aths** [comment]
ive already manually migrated the gshade stuff to reshade as of last night sorry, so can't try it out again. But i suspect it might have been giving me errors because i used a portable version of gshade, rather than the main installer, so my file structure etc would have been different since the program itself was never "installed" on my pc, only the configs and presets etc.

**Comment by MirisWisdom** [comment]
That makes perfect sense -- the thing checks for some system files which the portable version likely wouldn't include; will be improving the resilience for it.
